language: python
sudo: false
addons:
  firefox: "44.0.2"
python:
  - "2.7.6"
  - "2.7"
  - "3.6"
install:
  - pip install -U pip wheel
  - pip install -U setuptools
  - pip install -r requirements.txt
cache: pip
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - make flake8
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
