language: python
sudo: false
dist: xenial
addons:
  firefox: "45.0.2esr"
python:
  - "3.6"
install:
  - pip install -U pip wheel
  - pip install -U setuptools
  - pip install -r requirements.txt
cache: pip
services:
  - xvfb
script:
  - make flake8
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
