language: python
sudo: false
addons:
  firefox: "41.0.1"
python:
  - "2.7"
cache: pip
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - make
  - make behave
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
