db:
  image: postgres
web:
  image: ccnmtl/worth2
  environment:
    - APP=worth2
    - SECRET_KEY=dummy-secret-key
    - SETTINGS=settings_compose
  command: manage runserver 0.0.0.0:8000
  volumes:
    - .:/app/
  ports:
    - "8000:8000"
  links:
    - db
