# Generated by Django 2.1.9 on 2019-06-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssnm', '0004_auto_20150218_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='closeness',
            field=models.CharField(choices=[('VC', 'Very Close'), ('C', 'Close'), ('NC', 'Not Close')], default='VC', max_length=2),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='influence',
            field=models.CharField(choices=[('P', 'Positive'), ('MP', 'Mostly Positive'), ('MN', 'Mostly Negative'), ('N', 'Negative')], default='P', max_length=2),
        ),
    ]
