# Generated by Django 2.1.9 on 2019-06-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selftalk', '0004_refutationresponse_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refutation',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='statementblock',
            name='is_internal',
            field=models.BooleanField(default=True, help_text='If True, this will be rendered as a "My Self Talk" block. Otherwise this block\'s subject is a video.'),
        ),
        migrations.AlterField(
            model_name='statementblock',
            name='subject_name',
            field=models.TextField(blank=True, help_text='(optional) The name of the video subject for this block, e.g. "Jane"', null=True),
        ),
    ]
