# Generated by Django 2.1.9 on 2019-06-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protectivebehaviors', '0003_auto_20150223_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectivebehaviorsresults',
            name='quiz_class',
            field=models.CharField(default='protective-behaviors', help_text='Required', max_length=255),
        ),
    ]
