# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:02
from __future__ import unicode_literals

from django.db import migrations


def activate_participants(apps, schema_editor):
    """Activate each participant.

    Because users with is_active set to False can't be logged
    in through authenticate() anymore.
    """
    Participant = apps.get_model('main', 'Participant')
    for participant in Participant.objects.all():
        u = participant.user
        u.is_active = True
        u.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20151204_0916'),
    ]

    operations = [
        migrations.RunPython(activate_participants),
    ]
