# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-17 15:29
from __future__ import unicode_literals

from django.db import migrations


def remove_participants(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model('auth', 'User')
    qs = User.objects.filter(username__startswith='participant_')
    qs.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180111_1130'),
    ]

    operations = [
        migrations.RunPython(remove_participants),
    ]
