# Generated by Django 2.1.9 on 2019-06-19 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190617_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If this is the initial avatar for all participants, set this option to True. There can only be one default avatar in the system.'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='session_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('makeup', 'Make-Up')], default='regular', max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='cohort_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message="That cohort ID isn't valid. (It needs to be 3 digits)", regex='^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='study_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message="That study ID isn't valid. The format is: RRHHMMDDMMYBS", regex='^\\d\\d[0-2]\\d[0-5]\\d[0-3]\\d[0-1]\\d[5-9][1-5][1-2]$')]),
        ),
        migrations.AlterField(
            model_name='simpleimageblock',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='videoblock',
            name='video_id',
            field=models.CharField(help_text='The YouTube video id, e.g. "M7lc1UVf-VE"', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='watchedvideo',
            name='video_id',
            field=models.CharField(db_index=True, help_text='The youtube video ID', max_length=255, null=True),
        ),
    ]
