# Generated by Django 2.1.9 on 2019-06-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='location',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='section',
        ),
        migrations.RemoveField(
            model_name='inactiveuserprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inactiveuserprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='first_location',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='inactiveuserprofile_ptr',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='location',
        ),
        migrations.DeleteModel(
            name='Encounter',
        ),
        migrations.DeleteModel(
            name='InactiveUserProfile',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
