# Generated by Django 2.1.9 on 2019-06-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20190622_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='alt_text',
            field=models.TextField(default='alt_text'),
            preserve_default=False,
        ),
    ]
